name: Build Debug APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Debug
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AutoMathTapper-debug-apk
          path: app/build/outputs/apk/debug/*.apk
