name: Build Auto-Math-Tapper
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - run: ./gradlew --no-daemon clean assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Auto-Math-Tapper-APK
          path: app/build/outputs/apk/debug/app-debug.apk
